version: '2.0'

services:
  springboot:
    build: .
    container_name: springboot
    ports:
      - 8085:8080
    links:
      - neo4j
  neo4j:
    image: neo4j:3.5.0
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/123
    ports:
      - 7474:7474
      - 7687:7687
    
